# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YouBike-ObjC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

pod "FBSDKCoreKit"
pod "FBSDKLoginKit"
pod "FBSDKShareKit"
pod 'AFNetworking'

  # Pods for YouBike-ObjC

end
